# CSK Choir Hub API declaration (OpenAPI 3.0.4)
openapi: 3.2.0

info:
  title: CSK Choir Hub
  summary: This is the API declaration for CSK Choir Hub.
  contact:
    name: CSK Webbmästare
    email: webmasters@choir.chs.chalmers.se
  version: 1.0.0

servers:
  - url: http://localhost:5050/api
    description: Local development server
    name: local

security:
  - authCookie: []

paths:
  /books:
    $ref: '../routes/books/books.yaml#/paths/~1books'
  /books/{bookId}:
    $ref: '../routes/books/books.yaml#/paths/~1books~1{bookId}'
  /books/{bookId}/songs:
    $ref: '../routes/books/books.yaml#/paths/~1books~1{bookId}~1songs'
  /books/{bookId}/songs/{songId}:
    $ref: '../routes/books/books.yaml#/paths/~1books~1{bookId}~1songs~1{songId}'

  /events:
    $ref: '../routes/events/events.yaml#/paths/~1events'
  /events/{eventId}:
    $ref: '../routes/events/events.yaml#/paths/~1events~1{eventId}'
  /events/{eventId}/registrations:
    $ref: '../routes/events/events.yaml#/paths/~1events~1{eventId}~1registrations'
  /events/{eventId}/attendances:
    $ref: '../routes/events/events.yaml#/paths/~1events~1{eventId}~1attendances'

  /groups:
    $ref: '../routes/groups/groups.yaml#/paths/~1groups'
  /groups/{groupId}:
    $ref: '../routes/groups/groups.yaml#/paths/~1groups~1{groupId}'
  /groups/{groupId}/users:
    $ref: '../routes/groups/groups.yaml#/paths/~1groups~1{groupId}~1users'
  /groups/{groupId}/users/{userId}:
    $ref: '../routes/groups/groups.yaml#/paths/~1groups~1{groupId}~1users~1{userId}'
  /groups/{groupId}/children:
    $ref: '../routes/groups/groups.yaml#/paths/~1groups~1{groupId}~1children'
  /groups/{groupId}/children/{childGroupId}:
    $ref: '../routes/groups/groups.yaml#/paths/~1groups~1{groupId}~1children~1{childGroupId}'

  /roles:
    $ref: '../routes/roles/roles.yaml#/paths/~1roles'
  /roles/{roleId}:
    $ref: '../routes/roles/roles.yaml#/paths/~1roles~1{roleId}'
  /roles/{roleId}/users:
    $ref: '../routes/roles/roles.yaml#/paths/~1roles~1{roleId}~1users'
  /roles/{roleId}/users/{userId}:
    $ref: '../routes/roles/roles.yaml#/paths/~1roles~1{roleId}~1users~1{userId}'
  /roles/{roleId}/permissions:
    $ref: '../routes/roles/roles.yaml#/paths/~1roles~1{roleId}~1permissions'
  /roles/{roleId}/permissions/{permissionId}:
    $ref: '../routes/roles/roles.yaml#/paths/~1roles~1{roleId}~1permissions~1{permissionId}'

  /permissions:
    $ref: '../routes/permissions/permissions.yaml#/paths/~1permissions'
  /permissions/{permissionId}:
    $ref: '../routes/permissions/permissions.yaml#/paths/~1permissions~1{permissionId}'
  /permissions/{permissionId}/users:
    $ref: '../routes/permissions/permissions.yaml#/paths/~1permissions~1{permissionId}~1users'
  /permissions/{permissionId}/users/{userId}:
    $ref: '../routes/permissions/permissions.yaml#/paths/~1permissions~1{permissionId}~1users~1{userId}'

  /users:
    $ref: '../routes/users/users.yaml#/paths/~1users'

  /songs:
    $ref: '../routes/songs/songs.yaml#/paths/~1songs'
  /songs/{songId}:
    $ref: '../routes/songs/songs.yaml#/paths/~1songs~1{songId}'
  /songs/{songId}/tags:
    $ref: '../routes/songs/songs.yaml#/paths/~1songs~1{songId}~1tags'

  /tags:
    $ref: '../routes/tags/tags.yaml#/paths/~1tags'
  /tags/{tagId}:
    $ref: '../routes/tags/tags.yaml#/paths/~1tags~1{tagId}'

components:
  schemas:
    GroupType:
      $ref: './components.yaml#/schemas/GroupType'
    PermissionEffect:
      $ref: './components.yaml#/schemas/PermissionEffect'
    UserSummary:
      $ref: './components.yaml#/schemas/UserSummary'
    GroupReference:
      $ref: './components.yaml#/schemas/GroupReference'
    GroupMember:
      $ref: './components.yaml#/schemas/GroupMember'
    Group:
      $ref: './components.yaml#/schemas/Group'
    CreateGroupInput:
      $ref: './components.yaml#/schemas/CreateGroupInput'
    UpdateGroupInput:
      $ref: './components.yaml#/schemas/UpdateGroupInput'
    AddUserToGroupInput:
      $ref: './components.yaml#/schemas/AddUserToGroupInput'
    AddChildGroupInput:
      $ref: './components.yaml#/schemas/AddChildGroupInput'
    RoleReference:
      $ref: './components.yaml#/schemas/RoleReference'
    RoleUserAssignment:
      $ref: './components.yaml#/schemas/RoleUserAssignment'
    Role:
      $ref: './components.yaml#/schemas/Role'
    CreateRoleInput:
      $ref: './components.yaml#/schemas/CreateRoleInput'
    UpdateRoleInput:
      $ref: './components.yaml#/schemas/UpdateRoleInput'
    AssignUserToRoleInput:
      $ref: './components.yaml#/schemas/AssignUserToRoleInput'
    AddPermissionToRoleInput:
      $ref: './components.yaml#/schemas/AddPermissionToRoleInput'
    PermissionReference:
      $ref: './components.yaml#/schemas/PermissionReference'
    PermissionUserGrant:
      $ref: './components.yaml#/schemas/PermissionUserGrant'
    Permission:
      $ref: './components.yaml#/schemas/Permission'
    CreatePermissionInput:
      $ref: './components.yaml#/schemas/CreatePermissionInput'
    UpdatePermissionInput:
      $ref: './components.yaml#/schemas/UpdatePermissionInput'
    GrantUserPermissionInput:
      $ref: './components.yaml#/schemas/GrantUserPermissionInput'
    AdminUserGroupMembership:
      $ref: './components.yaml#/schemas/AdminUserGroupMembership'
    AdminUserRoleAssignment:
      $ref: './components.yaml#/schemas/AdminUserRoleAssignment'
    AdminUserPermissionGrant:
      $ref: './components.yaml#/schemas/AdminUserPermissionGrant'
    AdminUser:
      $ref: './components.yaml#/schemas/AdminUser'

    CSKEventType:
      $ref: './components.yaml#/schemas/CSKEventType'
    CSKEventSummary:
      $ref: './components.yaml#/schemas/CSKEventSummary'
    CSKEvent:
      $ref: './components.yaml#/schemas/CSKEvent'
    CreateEventInput:
      $ref: './components.yaml#/schemas/CreateEventInput'
    AttendanceStatus:
      $ref: './components.yaml#/schemas/AttendanceStatus'
    Attendance:
      $ref: './components.yaml#/schemas/Attendance'
    Registration:
      $ref: './components.yaml#/schemas/Registration'

    BookSummary:
      $ref: './components.yaml#/schemas/BookSummary'
    Book:
      $ref: './components.yaml#/schemas/Book'
    CreateBookInput:
      $ref: './components.yaml#/schemas/CreateBookInput'
    CreateSongInput:
      $ref: './components.yaml#/schemas/CreateSongInput'
    BookSong:
      $ref: './components.yaml#/schemas/BookSong'
    Song:
      $ref: './components.yaml#/schemas/Song'
    Tag:
      $ref: './components.yaml#/schemas/Tag'
    SongKnowledge:
      $ref: './components.yaml#/schemas/SongKnowledge'
    SongKnowledgeLevel:
      $ref: './components.yaml#/schemas/SongKnowledgeLevel'
    KnownSong:
      $ref: './components.yaml#/schemas/KnownSong'
    CSKVoice:
      $ref: './components.yaml#/schemas/CSKVoice'

    Error:
      $ref: './components.yaml#/schemas/Error'

  requestBodies:
    CreateEvent:
      $ref: './components.yaml#/requestBodies/CreateEvent'
    UpdateAttendance:
      $ref: './components.yaml#/requestBodies/UpdateAttendance'
    MakeRegistration:
      $ref: './components.yaml#/requestBodies/MakeRegistration'

  responses:
    ErrorResponse:
      $ref: './components.yaml#/responses/ErrorResponse'

  securitySchemes:
    authCookie:
      $ref: './components.yaml#/securitySchemes/authCookie'
